package com.rjb888.taskmaster.taskmasterapp.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "taskmaster")
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    UUID id;

    String title;
    String description;
    String status;

    public Task(){};

    public Task(String title, String description){
        this.title = title;
        this.description = description;
        this.status = "Available";
    }

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    public UUID getId(){
        return id;
    }


    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
